### ISSUE TITLE
Icon sizing issues

### ISSUE THREAD

**Issue by Jeremy-Walton** [RoleModel/rolemodel-design-system#60]
Icon styles currently set a line height but are using the wrong token variable. Additionally, some of the icons get rendered with an incorrect height.

We should add 
```scss
.material-symbols-outlined,
.material-symbols {
  line-height: var(--rm-line-height-densest);
  vertical-align: baseline;
}
```
To the icon styles to ensure the sizing of icons is correct.
